name: Thinker
markdown: kramdown
filter: 'tag'
# Use gitalk(https://github.com/gitalk/gitalk) comment function.
# true for use while false vise versa
use_gitalk: true
# Config encoding
encoding: utf-8
# Config timezone
# timezone: '-0800'
# Use amazing counters(http://www.amazingcounters.com) to collect statistics.
# true for use while false vise versa
use_amazing_counters: true
amazing_counters_account_id: 3225548